### ISSUE TITLE
Activities bundle

### ISSUE THREAD

**Issue by nukeador** [common-voice/mandarin#2]
Create a set of activities to support our goals in the coming months.

- [Working document](https://docs.google.com/document/d/146XX15ZnnpL__EYTjGYlrVH1wvlo-uLX0iDWR8k3beU/edit#heading=h.hy187lsrhjuc)
- [x] Get community review and test on the field

**Comment by irvin** [comment]
some of the resources I made last year,
https://discourse.mozilla.org/t/share-your-event-printing-materials/31471/2

we can also encourage people to share their resources.

**Comment by nukeador** [comment]
Community feedback and testing in progress during March

https://discourse.mozilla.org/t/feedback-common-voice-activity-bundles/36674/
