### ISSUE TITLE
Check if CV site is accessible from mainland China

### ISSUE THREAD

**Issue by nukeador** [common-voice/mandarin#5]

**Comment by nukeador** [comment]
@irvin @sammyfung Is this something you can get someone to check for us?

**Comment by irvin** [comment]
https://discourse.mozilla.org/t/issue-check-if-cv-site-is-accessible-from-mainland-china/36127
- I had pinged our l10n volunteer Meteor and Holy Wen to try
- I had asked the same question on China Mozillians weChat group, including ~70 core contributors

let’s wait for them to response

**Comment by irvin** [comment]
As with the response from multiple places, the website is working properly in China. 🎉

**Comment by mikehenrty** [comment]
Also note, that this information is available in Google Analytics, so you can continually check this without pinging the community.
